VMware module does not function on Python 3.12/3.13
/usr/local/salt/lib/python3.12/site-packages/salt/modules/linux_shadow.py:21: DeprecationWarning: 'spwd' is deprecated and slated for removal in Python 3.13
import spwd
[ERROR ] Failed to import module vsphere, this is due most likely to a syntax error:
Traceback (most recent call last):
File "/usr/local/salt/lib/python3.12/site-packages/salt/loader/lazy.py", line 806, in _load_module
spec.loader.exec_module(mod)
File "", line 995, in exec_module
File "", line 488, in _call_with_frames_removed
File "/usr/local/salt/lib/python3.12/site-packages/salt/modules/vsphere.py", line 193, in
import salt.utils.pbm
File "/usr/local/salt/lib/python3.12/site-packages/salt/utils/pbm.py", line 42, in
import salt.utils.vmware
File "", line 1360, in _find_and_load
File "", line 1331, in _find_and_load_unlocked
File "", line 935, in _load_unlocked
File "", line 991, in exec_module
File "", line 1124, in get_code
File "", line 753, in _compile_bytecode
EOFError: marshal data too short
[ERROR ] Failed to import pillar vmware_pillar, this is due most likely to a syntax error:
Traceback (most recent call last):
File "/usr/local/salt/lib/python3.12/site-packages/salt/loader/lazy.py", line 806, in _load_module
spec.loader.exec_module(mod)
File "", line 995, in exec_module
File "", line 488, in _call_with_frames_removed
File "/usr/local/salt/lib/python3.12/site-packages/salt/pillar/vmware_pillar.py", line 148, in
import salt.utils.vmware